version: '2'

services:
  ciinabox:
    hostname: ciinabox
    image: stono/ciinabox
    build: .
    volumes:
      - ./:/app
      - ./.docker/config:/root/.config
      - ./.docker/kube:/root/.kube
