version: '2'

services:
  ciinabox:
    image: stono/ciinabox
    build: .
    volumes:
      - ./.env:/app/.env
      - ./.tmp:/app/.tmp
      - ./.docker/config:/root/.config
      - ./.docker/kube:/root/.kube
