apiVersion: v1
kind: Service
metadata:
  name: gocd-master
  labels:
    app: gocd-master
spec:
  ports:
  - port: 8153
    name: web
    targetPort: 8153
  - port: 8154
    name: agent
    targetPort: 8154
  selector:
    app: gocd-master
