apiVersion: v1
kind: Service
metadata:
  name: gocd-nginx
  labels:
    app: gocd-nginx
spec:
  type: LoadBalancer
  loadBalancerIP: {{ENV.GOCD_MASTER_IP}} 
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
  selector:
    app: gocd-nginx
