#!/bin/bash
set -e
source "$(dirname $0)/common.sh"

display_usage_and_exit() {
  echo "Usage: $(basename "$0") [preprod | prod]"
  exit 1
}

apply_common_configuration() {
  for f in `find $ROOT/configuration/common -type f -name "*.yml"`; do
    echo "Applying common configuration: $f"
    pdata app deploy $f 
  done
}

apply_environment_specific_configuration() {
  for f in `find $ROOT/configuration/$env -type f -name "*.yml"`; do
    echo "Applying environment configuration: $f"
    pdata app deploy $f 
  done
}

apply_kubernetes_configuration() {
  apply_common_configuration
  apply_environment_specific_configuration $1
}

readonly env="${1:-}"
readonly cluster_name="$STACK_NAME-$env"

check_presence "$env"
apply_kubernetes_configuration "$env"
